package interfaces;

import java.awt.Toolkit;
import java.awt.Image;
import java.net.URL;
import entidades.Cliente;
import dados.ClienteDados;
import dados.DadosException;

/**
 * @author BIC-Jr Guia de Estilo
 */
public class ClienteExcluir extends javax.swing.JDialog {

    public ClienteExcluir(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        alterarIcone();
        preencherCampos(cliente);
    }

    public boolean getOpcao() {
        return opcao;
    }

    private void alterarIcone() {
        URL url = this.getClass().getResource("/imagens/usuario.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        this.setLocationRelativeTo(null);
        util.JanelaComum.setAcessibilidade(this);
    }

    private void preencherCampos(Cliente cliente) {
        rotuloNome.setText("Nome: " + cliente.getNmCliente());
        rotuloCpf.setText("CPF: " + cliente.getCpf());
        rotuloEmail.setText("E-mail: " + cliente.getEmail());
        rotuloTelefone.setText("Telefone " + cliente.getObservacao() + ": " + cliente.getTelefone());
        codigo = cliente.getCdCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTela = new javax.swing.JScrollPane();
        painelFormulario = new javax.swing.JPanel();
        rotuloMensagem = new javax.swing.JLabel();
        rotuloNome = new javax.swing.JLabel();
        rotuloCpf = new javax.swing.JLabel();
        rotuloEmail = new javax.swing.JLabel();
        botaoNao = new javax.swing.JButton();
        botaoSim = new javax.swing.JButton();
        rotuloTelefone = new javax.swing.JLabel();
        painelTitulo = new javax.swing.JPanel();
        rotuloNovoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Clientes");
        setMaximumSize(new java.awt.Dimension(530, 285));
        setMinimumSize(new java.awt.Dimension(530, 285));
        setPreferredSize(new java.awt.Dimension(530, 285));
        setResizable(false);

        painelTela.setBorder(null);

        painelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rotuloMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloMensagem.setText("Você tem certeza de que deseja excluir este cliente?");
        painelFormulario.add(rotuloMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        rotuloNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloNome.setText("Nome: Regina Maria Souza Carvalho");
        painelFormulario.add(rotuloNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        rotuloCpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloCpf.setText("CPF: 123.456.789-00");
        painelFormulario.add(rotuloCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        rotuloEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloEmail.setText("E-mail: regina.msc@negocios.com");
        painelFormulario.add(rotuloEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        botaoNao.setBackground(new java.awt.Color(135, 206, 235));
        botaoNao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoNao.setMnemonic('n');
        botaoNao.setText("Não");
        botaoNao.setToolTipText("Fechar janela sem excluir cliente (Alt+N)");
        botaoNao.setContentAreaFilled(false);
        botaoNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoNao.setOpaque(true);
        botaoNao.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNaoActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoNao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 35));

        botaoSim.setBackground(new java.awt.Color(46, 139, 87));
        botaoSim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSim.setMnemonic('s');
        botaoSim.setText("Sim");
        botaoSim.setToolTipText("Confirmar exclusão do cliente (Alt+S)");
        botaoSim.setContentAreaFilled(false);
        botaoSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSim.setOpaque(true);
        botaoSim.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, 35));

        rotuloTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloTelefone.setText("Telefone: (00) 12345-6789 - Celular");
        painelFormulario.add(rotuloTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        painelTela.setViewportView(painelFormulario);

        getContentPane().add(painelTela, java.awt.BorderLayout.CENTER);

        painelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        rotuloNovoCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rotuloNovoCliente.setForeground(new java.awt.Color(255, 255, 255));
        rotuloNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarioApagar.png"))); // NOI18N
        rotuloNovoCliente.setText("EXCLUIR CLIENTE");
        painelTitulo.add(rotuloNovoCliente);

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNaoActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoNaoActionPerformed

    private void botaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimActionPerformed
        opcao = true;
        try {
            ClienteDados.excluir(codigo);
        } catch (DadosException ex) {
            Problema erroDeConexao = new Problema(new javax.swing.JFrame(), true, ex.getMessage());
            erroDeConexao.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_botaoSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ClienteExcluir dialog = new ClienteExcluir(new javax.swing.JFrame(), true, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private boolean opcao = false;
    private int codigo = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoNao;
    private javax.swing.JButton botaoSim;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JScrollPane painelTela;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel rotuloCpf;
    private javax.swing.JLabel rotuloEmail;
    private javax.swing.JLabel rotuloMensagem;
    private javax.swing.JLabel rotuloNome;
    private javax.swing.JLabel rotuloNovoCliente;
    private javax.swing.JLabel rotuloTelefone;
    // End of variables declaration//GEN-END:variables
}
