package interfaces;

import java.awt.Toolkit;
import java.awt.Image;
import java.net.URL;

/**
 * @author BIC-Jr Guia de Estilo
 */
public class Problema extends javax.swing.JDialog {

    public Problema(java.awt.Frame parent, boolean modal, String erro) {
        super(parent, modal);
        initComponents();
        alterarIcone();
        preencherCampos(erro);
    }

    private void alterarIcone() {
        URL url = this.getClass().getResource("/imagens/logoSalao.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        this.setLocationRelativeTo(null);
        util.JanelaComum.setAcessibilidade(this);
    }
    
    private void preencherCampos(String erro) {
        erro = erro.replace("to the server", "to the<br>server");
        erro = erro.replace("packets", "packets<br>");
        rotuloErro.setText(erro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelFormulario = new javax.swing.JPanel();
        botaoSim = new javax.swing.JButton();
        rotuloMensagem = new javax.swing.JLabel();
        botaoDetalhes = new javax.swing.JButton();
        painelDescricao = new javax.swing.JScrollPane();
        rotuloErro = new javax.swing.JLabel();
        painelTitulo = new javax.swing.JPanel();
        rotuloAtencao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recanto Beleza");
        setMaximumSize(new java.awt.Dimension(510, 500));
        setMinimumSize(new java.awt.Dimension(510, 340));
        setPreferredSize(new java.awt.Dimension(510, 340));
        setResizable(false);

        painelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoSim.setBackground(new java.awt.Color(46, 139, 87));
        botaoSim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSim.setMnemonic('o');
        botaoSim.setText("OK");
        botaoSim.setToolTipText("Fechar esta janela (Alt-O)");
        botaoSim.setContentAreaFilled(false);
        botaoSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSim.setOpaque(true);
        botaoSim.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 130, 35));

        rotuloMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloMensagem.setText("<html><p align=\"justify\">O sistema não conseguiu se conectar ao banco de dados. Isso pode ser<br>solucionado de uma das seguintes formas:</p><p align=\"justify\"><br>&#8212 Verifique se o XAMPP (ou o programa similar que você usa) foi aberto, se não, inicialize-o.</p><br><p align=\"justify\">&#8212 Certifique-se de que o script \"bancoBicJrGuiaEstilo.sql\" enviado com o<br>projeto já foi executado neste computador.</p><br> <p align=\"justify\">Você também pode nos contatar pelo e-mail: bic@sistemas.com.br.</p></html>");
        painelFormulario.add(rotuloMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 470, 200));

        botaoDetalhes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        botaoDetalhes.setMnemonic('d');
        botaoDetalhes.setText("Detalhes");
        botaoDetalhes.setToolTipText("Mostrar mais informações acerca do ocorrido (Alt-D)");
        botaoDetalhes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoDetalhes.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDetalhesActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 35));
        botaoDetalhes.setOpaque(true);

        rotuloErro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloErro.setText("jLabel1");
        rotuloErro.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rotuloErro.setAlignmentX(1.0F);
        painelDescricao.setViewportView(rotuloErro);

        painelFormulario.add(painelDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 460, 140));

        getContentPane().add(painelFormulario, java.awt.BorderLayout.CENTER);

        painelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        rotuloAtencao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rotuloAtencao.setForeground(new java.awt.Color(255, 255, 255));
        rotuloAtencao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/erro.png"))); // NOI18N
        rotuloAtencao.setText("ATENÇÃO");
        painelTitulo.add(rotuloAtencao);

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSimActionPerformed

    private void botaoDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDetalhesActionPerformed
        if(visivel) {
            painelDescricao.setVisible(false);
            this.setSize(510, 340);
            botaoDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png")));
            visivel = false;
        } else if (!visivel) {
            visivel = true;
            painelDescricao.setVisible(true);
            this.setSize(510, 500);
            botaoDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menos.png")));
        }
    }//GEN-LAST:event_botaoDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Problema dialog = new Problema(new javax.swing.JFrame(), true, null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    
    boolean visivel = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDetalhes;
    private javax.swing.JButton botaoSim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane painelDescricao;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel rotuloAtencao;
    private javax.swing.JLabel rotuloErro;
    private javax.swing.JLabel rotuloMensagem;
    // End of variables declaration//GEN-END:variables
}
