package interfaces;

import java.awt.Toolkit;
import java.awt.Image;
import java.net.URL;

/**
 * @author BIC-Jr Guia de Estilo
 */
public class ServicoAdicionar extends javax.swing.JDialog {

    public ServicoAdicionar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        alterarIcone();
    }

    public boolean getOpcao() {
        return opcao;
    }

    public String getTexto() {
        return texto;
    }

    private void alterarIcone() {
        URL url = this.getClass().getResource("/imagens/calendario.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        this.setLocationRelativeTo(null);
        util.JanelaComum.setAcessibilidade(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTela = new javax.swing.JScrollPane();
        painelFormulario = new javax.swing.JPanel();
        rotuloMensagem = new javax.swing.JLabel();
        botaoCancelar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();
        painelAreaTexto = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        painelTitulo = new javax.swing.JPanel();
        rotuloTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Atendimentos");
        setMaximumSize(new java.awt.Dimension(385, 265));
        setMinimumSize(new java.awt.Dimension(385, 265));
        setPreferredSize(new java.awt.Dimension(385, 265));
        setResizable(false);

        painelTela.setBorder(null);

        painelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rotuloMensagem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloMensagem.setText("Detalhes do Serviço*:");
        painelFormulario.add(rotuloMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        botaoCancelar.setBackground(new java.awt.Color(135, 206, 235));
        botaoCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoCancelar.setMnemonic('c');
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setToolTipText("Cancelar adição de detalhes (Alt-C)");
        botaoCancelar.setContentAreaFilled(false);
        botaoCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCancelar.setOpaque(true);
        botaoCancelar.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, 35));

        botaoSalvar.setBackground(new java.awt.Color(153, 153, 153));
        botaoSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSalvar.setMnemonic('s');
        botaoSalvar.setText("Salvar");
        botaoSalvar.setToolTipText("Salvar adição de detalhes (Alt-S)");
        botaoSalvar.setContentAreaFilled(false);
        botaoSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSalvar.setEnabled(false);
        botaoSalvar.setOpaque(true);
        botaoSalvar.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 130, 35));

        areaTexto.setColumns(20);
        areaTexto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        areaTexto.setRows(4);
        areaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                areaTextoKeyReleased(evt);
            }
        });
        painelAreaTexto.setViewportView(areaTexto);

        painelFormulario.add(painelAreaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 90));

        painelTela.setViewportView(painelFormulario);

        getContentPane().add(painelTela, java.awt.BorderLayout.CENTER);

        painelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        rotuloTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rotuloTitulo.setForeground(new java.awt.Color(255, 255, 255));
        rotuloTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servicoAdicionar.png"))); // NOI18N
        rotuloTitulo.setText("ADICIONAR DETALHES");
        painelTitulo.add(rotuloTitulo);

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        opcao = true;
        texto = areaTexto.getText();
        this.dispose();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void areaTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTextoKeyReleased
        if (areaTexto.getText().equals("")) {
            botaoSalvar.setEnabled(false);
            botaoSalvar.setBackground(new java.awt.Color(153,153,153));
        } else {
            botaoSalvar.setEnabled(true);
            botaoSalvar.setBackground(new java.awt.Color(46, 139, 87));
        }
    }//GEN-LAST:event_areaTextoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServicoAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ServicoAdicionar dialog = new ServicoAdicionar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    private boolean opcao = false;
    private String texto = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JScrollPane painelAreaTexto;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JScrollPane painelTela;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel rotuloMensagem;
    private javax.swing.JLabel rotuloTitulo;
    // End of variables declaration//GEN-END:variables
}
