package interfaces;

import java.awt.Toolkit;
import java.awt.Image;
import java.net.URL;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * @author BIC-Jr Guia de Estilo
 */
public class Sobre extends javax.swing.JDialog {

    public Sobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        alterarIcone();
    }

    private void alterarIcone() {
        URL url = this.getClass().getResource("/imagens/logoSalao.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        this.setLocationRelativeTo(null);
        util.JanelaComum.setAcessibilidade(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelTela = new javax.swing.JScrollPane();
        painelFormulario = new javax.swing.JPanel();
        linkChristiano = new javax.swing.JLabel();
        linkPaula = new javax.swing.JLabel();
        linkMarcelo = new javax.swing.JLabel();
        linkDeisymar = new javax.swing.JLabel();
        rotuloChristiano = new javax.swing.JLabel();
        rotuloPaula = new javax.swing.JLabel();
        rotuloDeisymar = new javax.swing.JLabel();
        rotuloMarcelo = new javax.swing.JLabel();
        rotuloOdilon = new javax.swing.JLabel();
        linkOdilon = new javax.swing.JLabel();
        rotuloAtualizacao = new javax.swing.JLabel();
        rotuloFicticia = new javax.swing.JLabel();
        rotuloGuiaDeEstilo = new javax.swing.JLabel();
        botaoSim = new javax.swing.JButton();
        painelAreaTexto = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        rotuloCefetmg = new javax.swing.JLabel();
        painelTitulo = new javax.swing.JPanel();
        rotuloSobre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recanto Beleza");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(675, 560));
        setResizable(false);

        painelTela.setBorder(null);

        painelFormulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linkChristiano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/janela.png"))); // NOI18N
        linkChristiano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkChristiano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkChristianoMouseClicked(evt);
            }
        });
        painelFormulario.add(linkChristiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 118, -1, -1));

        linkPaula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/janela.png"))); // NOI18N
        linkPaula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkPaula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkPaulaMouseClicked(evt);
            }
        });
        painelFormulario.add(linkPaula, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 118, -1, -1));

        linkMarcelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/janela.png"))); // NOI18N
        linkMarcelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkMarcelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMarceloMouseClicked(evt);
            }
        });
        painelFormulario.add(linkMarcelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 170, -1, -1));

        linkDeisymar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/janela.png"))); // NOI18N
        linkDeisymar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkDeisymar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkDeisymarMouseClicked(evt);
            }
        });
        painelFormulario.add(linkDeisymar, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 170, -1, -1));

        rotuloChristiano.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloChristiano.setForeground(java.awt.Color.blue);
        rotuloChristiano.setText("<html><u>Christiano de Souza Oliveira</u></html>");
        rotuloChristiano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloChristiano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotuloChristianoMouseClicked(evt);
            }
        });
        painelFormulario.add(rotuloChristiano, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 113, 190, -1));

        rotuloPaula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloPaula.setForeground(java.awt.Color.blue);
        rotuloPaula.setText("<html><u>Paula Arthuso Carvalho</u></html>");
        rotuloPaula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloPaula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotuloPaulaMouseClicked(evt);
            }
        });
        painelFormulario.add(rotuloPaula, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 113, 190, -1));

        rotuloDeisymar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloDeisymar.setForeground(java.awt.Color.blue);
        rotuloDeisymar.setText("<html><u>Deisymar Botega Tavares</u></html>");
        rotuloDeisymar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloDeisymar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotuloDeisymarMouseClicked(evt);
            }
        });
        painelFormulario.add(rotuloDeisymar, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 165, 190, -1));

        rotuloMarcelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloMarcelo.setForeground(java.awt.Color.blue);
        rotuloMarcelo.setText("<html><u>Marcelo de Sousa Balbino</u></html>");
        rotuloMarcelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloMarcelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotuloMarceloMouseClicked(evt);
            }
        });
        painelFormulario.add(rotuloMarcelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 165, 190, -1));

        rotuloOdilon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloOdilon.setForeground(java.awt.Color.blue);
        rotuloOdilon.setText("<html><u>Odilon Corrêa da Silva</u></html>");
        rotuloOdilon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rotuloOdilon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rotuloOdilonMouseClicked(evt);
            }
        });
        painelFormulario.add(rotuloOdilon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 165, 150, -1));

        linkOdilon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/janela.png"))); // NOI18N
        linkOdilon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        linkOdilon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkOdilonMouseClicked(evt);
            }
        });
        painelFormulario.add(linkOdilon, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 170, -1, -1));

        rotuloAtualizacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloAtualizacao.setForeground(new java.awt.Color(0, 0, 0));
        rotuloAtualizacao.setText("<html><i>Última atualização: <strong>18/07/2019.</strong></i></html>");
        painelFormulario.add(rotuloAtualizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        rotuloFicticia.setText("<html><i>Recanto Beleza</i> é uma empresa <strong>fictícia.</strong></html>");
        painelFormulario.add(rotuloFicticia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 200, 20));

        rotuloGuiaDeEstilo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloGuiaDeEstilo.setText("<html><i>Guia de Estilo</i></html>");
        painelFormulario.add(rotuloGuiaDeEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 46, -1, -1));

        botaoSim.setBackground(new java.awt.Color(135, 206, 235));
        botaoSim.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoSim.setMnemonic('v');
        botaoSim.setText("Voltar");
        botaoSim.setToolTipText("Fechar esta janela (Alt-V)");
        botaoSim.setContentAreaFilled(false);
        botaoSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoSim.setOpaque(true);
        botaoSim.setPreferredSize(new java.awt.Dimension(130, 35));
        botaoSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSimActionPerformed(evt);
            }
        });
        painelFormulario.add(botaoSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 130, 35));

        areaTexto.setEditable(false);
        areaTexto.setBackground(new java.awt.Color(240, 240, 240));
        areaTexto.setColumns(20);
        areaTexto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        areaTexto.setForeground(new java.awt.Color(0, 0, 0));
        areaTexto.setRows(5);
        areaTexto.setText("\n  Este sistema foi concebido, projetado e desenvolvido pela equipe do Projeto de Iniciação\n  Científica Voluntária Júnior (PICV-Jr)                        do CEFET-MG Câmpus Timóteo de\n  agosto de 2018 até julho de 2019, composta:\n\n    pelos estudantes:\n                                                            e                                          ;\n                                                                                         \n    e pelos professores:\n                                                      ,                                                e                                         .\n\n  A intenção deste projeto de iniciação científica é proporcionar uma melhor experiência\n  de aprendizado da engenharia de usabilidade e da interação com sistemas pensados\n  segundo as heurísticas indicadas por estudiosos da área, depois estudadas e compiladas.\n\n  ");
        areaTexto.setFocusable(false);
        painelAreaTexto.setViewportView(areaTexto);

        painelFormulario.add(painelAreaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 610, 295));

        rotuloCefetmg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rotuloCefetmg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cefetmg.png"))); // NOI18N
        painelFormulario.add(rotuloCefetmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, 90));

        painelTela.setViewportView(painelFormulario);

        getContentPane().add(painelTela, java.awt.BorderLayout.CENTER);

        painelTitulo.setBackground(new java.awt.Color(0, 0, 0));

        rotuloSobre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rotuloSobre.setForeground(new java.awt.Color(255, 255, 255));
        rotuloSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobreJanela.png"))); // NOI18N
        rotuloSobre.setText("SOBRE");
        painelTitulo.add(rotuloSobre);

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSimActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoSimActionPerformed

    private void rotuloChristianoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotuloChristianoMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/0330061632763129"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_rotuloChristianoMouseClicked

    private void rotuloPaulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotuloPaulaMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/0586083831246279"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_rotuloPaulaMouseClicked

    private void rotuloDeisymarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotuloDeisymarMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/2446784976283439"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_rotuloDeisymarMouseClicked

    private void rotuloMarceloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotuloMarceloMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/6890179112274993"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_rotuloMarceloMouseClicked

    private void linkChristianoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkChristianoMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/0330061632763129"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_linkChristianoMouseClicked

    private void linkPaulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkPaulaMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/0586083831246279"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_linkPaulaMouseClicked

    private void linkDeisymarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkDeisymarMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/2446784976283439"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_linkDeisymarMouseClicked

    private void linkMarceloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMarceloMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/6890179112274993"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_linkMarceloMouseClicked

    private void rotuloOdilonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotuloOdilonMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/4641531678975028"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_rotuloOdilonMouseClicked

    private void linkOdilonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkOdilonMouseClicked
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new java.net.URI("http://lattes.cnpq.br/4641531678975028"));
        } catch (IOException | URISyntaxException e) {}
    }//GEN-LAST:event_linkOdilonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Sobre dialog = new Sobre(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton botaoSim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel linkChristiano;
    private javax.swing.JLabel linkDeisymar;
    private javax.swing.JLabel linkMarcelo;
    private javax.swing.JLabel linkOdilon;
    private javax.swing.JLabel linkPaula;
    private javax.swing.JScrollPane painelAreaTexto;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JScrollPane painelTela;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel rotuloAtualizacao;
    private javax.swing.JLabel rotuloCefetmg;
    private javax.swing.JLabel rotuloChristiano;
    private javax.swing.JLabel rotuloDeisymar;
    private javax.swing.JLabel rotuloFicticia;
    private javax.swing.JLabel rotuloGuiaDeEstilo;
    private javax.swing.JLabel rotuloMarcelo;
    private javax.swing.JLabel rotuloOdilon;
    private javax.swing.JLabel rotuloPaula;
    private javax.swing.JLabel rotuloSobre;
    // End of variables declaration//GEN-END:variables
}
